# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Orianna's Kingdom
SEOTitle: 博客 | Orianna's Kingdom
brief-intro: Master My Life
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
description_footer: Master My Life
baseurl: ""                             # the subpath of your site, e.g. /blog
url: "http://orianna-zzo.github.io"     # the base hostname & protocol for your site
permalinks: pretty


# SNS links
github_username: orianna-zzo
# facebook_username: 
# twitter_username: 
linkedIn_username: ziouzheng
# weibo_username: 
# zhihu_username: 
email: zhengziou@gmail.com
RSS: false


# Build settings
markdown: kramdown
highlight: rouge
paginate: 10                            # Number of posts in one page


# # Gems
# # from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

   
# Sidebar settings
# sidebar: true                           # whether or not using Sidebar.
# sidebar-about-description: "Master My Life"
# sidebar-avatar: /images/common/Me_2013-11-24.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
# featured-tags: true                     # whether or not using Feature-Tags
# featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

   
# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: 
# disqus_shortname: #gaohaoyang

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
# google_analytics_id: UA-72449510-4 # google 分析追踪id
